#ifndef CZAR_LOAD_AST_H
#define CZAR_LOAD_AST_H

#include "node.h"
#include <fstream>
#include <iostream>
#include <sstream>

/**
 * @brief Turnes a .def file into a list of nodes with correct node attributes
 * 
 * @param filePath Path to the CZAR .def file
 */
void readInput(string filePath);

/**
 * @brief Turns the list of nodes generated by readInput into a CZAR
 *        style AST 
 * 
 * @param filePath The path for the .def file same as used in readInput
 * @return Node* Returns the pointer to the root node of the AST
 */
Node *loadTree(string filePath);

/**
 * @brief Get the Nodes object
 * 
 * @return vector<Node>* 
 */
vector<Node>* getNodes();

#endif